version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: renataaline
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/escola
      SPRING_DATASOURCE_USERNAME: renataaline
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres-data:
